import Head from 'next/head';
import Icons from '../components/Icons';
import Header from '../components/Header';
import Gallery from '../components/Gallery';
import HomeNews from '../components/HomeNews';
import ShowRoom from '../components/ShowRoom';
import HomeAbout from '../components/HomeAbout';
import TopProducts from '../components/TopProducts';
import Infografics from '../components/Infografics';
import HomeCategories from '../components/HomeCategories';
import SliderCategories from '../components/SliderCategories';

export default function Home() {
  return (
    <>
      <Head>
        <title>NOTKA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='icons' href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />

      </Head>
      <div className='Home'>
        <Header />
        <SliderCategories />
        <HomeCategories />
        <TopProducts />
        <HomeAbout />
        <HomeNews />
        <ShowRoom />
        <Infografics />
        <Icons />
        <Gallery />
      </div>
    </>
  )
}
