import Head from 'next/head';
import Header from '../components/Header';
import HomeAbout from '../components/HomeAbout';
import HomeCategories from '../components/HomeCategories';
import SliderCategories from '../components/SliderCategories';
import TopProducts from '../components/TopProducts';

export default function Home() {
  return (
    <>
      <Head>
        <title>NOTKA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel='icons'
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />

      </Head>
      <div className='Home'>
        <Header />
        <SliderCategories />
        <HomeCategories />
        <TopProducts />
        <HomeAbout />
      </div>
    </>
  )
}
