import Head from 'next/head';
import style from '../styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App with Yarn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`parent ${style.Home}`}>
        <div className={`wrapper ${style.wrapper}`}>
          <h1 className={`title`}>Hello world</h1>
        </div>
      </div>
    </>
  )
}
